struct DepthSpacePoint
{
	float X;
	float Y;
};

int4 readPixel(RWStructuredBuffer<int4> buffer, int x, int y)
{
	int4 output;
	uint index = (x + y * 1080);

	// TODO

	return output;
}

RWStructuredBuffer<int4> bgra;
RWStructuredBuffer<uint> depth;
RWStructuredBuffer<DepthSpacePoint> depthSpaceData;
RWTexture2D<int> result;

[numthreads(1, 1, 1)]
void Filter(uint3 threadID : SV_DispatchThreadID)
{
	result[threadID.xy] = readPixel(bgra, 0, 0);
}